name: Test

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq libuv1-dev libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev -y
        python -m pip install --upgrade pip
        pip install mys
    - name: Test
      run: |
        mys test
        (cd examples/tetris && mys build)

  release:
    needs: [linux]
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags')

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mys
    - name: Publish release to mys-lang.org
      run: |
        mys publish -t ${{secrets.publish_token}}
